class Config:
    DEFAULT_MINUTES = 120
    MIN_MINUTES = 10
    MAX_MINUTES = 500
    MAX_HISTORY_RECORDS = 250
    DEFAULT_LAMBDA = 5
    DEFAULT_THRESHOLD = 0.05
    MIN_THRESHOLD = 0.001
    MAX_THRESHOLD = 0.5
    MIN_LAMBDA = 1
    MAX_LAMBDA = 20
